apiVersion: v1
data:
  default.conf: |2-

    # Создайте конфиг мап из файла `default.conf` с конфигурацией nginx.
    # kubectl create configmap app --from-file default.conf
    server {
        listen       80 default_server;
        server_name  _;

        default_type text/plain;

        location / {
            return 200 '$hostname request: $request_uri\n';
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-01T09:44:41Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:default.conf: {}
    manager: kubectl
    operation: Update
    time: "2020-05-01T09:44:41Z"
  name: app
  namespace: default
  resourceVersion: "304396"
  selfLink: /api/v1/namespaces/default/configmaps/app
  uid: fd9e50e2-1572-49a1-a60a-bdc1779ecc91
